# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitProject\PythonProjects\pyqt_study\calculator_number\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(833, 506)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 110, 411, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color:rgb(126, 126, 126);\n"
"border:1px;\n"
"border-bottom:0px;\n"
"border-style: solid;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color:rgb(126, 126, 126);\n"
"border:1px;\n"
"border-top:0px;\n"
"border-style: solid;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.button_b = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_b.setFont(font)
        self.button_b.setAutoFillBackground(False)
        self.button_b.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_b.setObjectName("button_b")
        self.gridLayout.addWidget(self.button_b, 0, 0, 1, 3)
        self.button_l = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_l.setFont(font)
        self.button_l.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_l.setObjectName("button_l")
        self.gridLayout.addWidget(self.button_l, 1, 3, 1, 1)
        self.button_0 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 4, 0, 1, 1)
        self.button_ce = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_ce.setFont(font)
        self.button_ce.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_ce.setObjectName("button_ce")
        self.gridLayout.addWidget(self.button_ce, 0, 3, 1, 1)
        self.button_1 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 3, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("color:rgb(255, 0, 0)")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 4, 4, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 2, 4, 1, 1)
        self.button_s = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_s.setFont(font)
        self.button_s.setObjectName("button_s")
        self.gridLayout.addWidget(self.button_s, 1, 4, 1, 1)
        self.button_e = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_e.setFont(font)
        self.button_e.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_e.setObjectName("button_e")
        self.gridLayout.addWidget(self.button_e, 3, 3, 1, 1)
        self.button_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 3, 1, 1, 1)
        self.button_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.button_o = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_o.setFont(font)
        self.button_o.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_o.setObjectName("button_o")
        self.gridLayout.addWidget(self.button_o, 2, 3, 1, 1)
        self.button_9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 1, 2, 1, 1)
        self.button_t = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_t.setFont(font)
        self.button_t.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_t.setObjectName("button_t")
        self.gridLayout.addWidget(self.button_t, 4, 3, 1, 1)
        self.button_c = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_c.setFont(font)
        self.button_c.setStyleSheet("color:rgb(255, 0, 0)")
        self.button_c.setObjectName("button_c")
        self.gridLayout.addWidget(self.button_c, 0, 4, 1, 1)
        self.button_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 2, 2, 1, 1)
        self.button_7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 1, 0, 1, 1)
        self.button_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 2, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 4, 1, 1, 1)
        self.button_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 3, 2, 1, 1)
        self.button_8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 3, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "计算器"))
        self.label_2.setText(_translate("mainWindow", "7"))
        self.button_b.setText(_translate("mainWindow", "Backspace"))
        self.button_l.setText(_translate("mainWindow", "/"))
        self.button_0.setText(_translate("mainWindow", "0"))
        self.button_ce.setText(_translate("mainWindow", "CE"))
        self.button_1.setText(_translate("mainWindow", "1"))
        self.pushButton_20.setText(_translate("mainWindow", "="))
        self.pushButton_21.setText(_translate("mainWindow", "%"))
        self.button_s.setText(_translate("mainWindow", "sqr"))
        self.button_e.setText(_translate("mainWindow", "-"))
        self.button_2.setText(_translate("mainWindow", "2"))
        self.button_5.setText(_translate("mainWindow", "5"))
        self.pushButton_12.setText(_translate("mainWindow", "."))
        self.button_o.setText(_translate("mainWindow", "*"))
        self.button_9.setText(_translate("mainWindow", "9"))
        self.button_t.setText(_translate("mainWindow", "+"))
        self.button_c.setText(_translate("mainWindow", "C"))
        self.button_6.setText(_translate("mainWindow", "6"))
        self.button_7.setText(_translate("mainWindow", "7"))
        self.button_4.setText(_translate("mainWindow", "4"))
        self.pushButton_16.setText(_translate("mainWindow", "+/-"))
        self.button_3.setText(_translate("mainWindow", "3"))
        self.button_8.setText(_translate("mainWindow", "8"))
        self.pushButton_23.setText(_translate("mainWindow", "1/x"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
