# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitProject\PythonProjects\pyqt_study\menu\pull_down.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 367)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 559, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_text = QtWidgets.QMenu(self.menu)
        self.menu_text.setObjectName("menu_text")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.action_name = QtWidgets.QAction(MainWindow)
        self.action_name.setObjectName("action_name")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.actioncolor = QtWidgets.QAction(MainWindow)
        self.actioncolor.setObjectName("actioncolor")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu_text.addAction(self.action_1)
        self.menu_text.addAction(self.action_2)
        self.menu_text.addAction(self.action_3)
        self.menu.addAction(self.action_name)
        self.menu.addAction(self.menu_text.menuAction())
        self.menu_2.addAction(self.actioncolor)
        self.menu_3.addAction(self.actionexit)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "下拉式菜单示例"))
        self.label.setText(_translate("MainWindow", "下拉式菜单"))
        self.menu.setTitle(_translate("MainWindow", "字体"))
        self.menu_text.setTitle(_translate("MainWindow", "文本风格"))
        self.menu_2.setTitle(_translate("MainWindow", "颜色"))
        self.menu_3.setTitle(_translate("MainWindow", "结束"))
        self.action_name.setText(_translate("MainWindow", "字体名称"))
        self.action_1.setText(_translate("MainWindow", "粗体"))
        self.action_2.setText(_translate("MainWindow", "斜体"))
        self.action_3.setText(_translate("MainWindow", "下划线"))
        self.actioncolor.setText(_translate("MainWindow", "颜色设置"))
        self.actionexit.setText(_translate("MainWindow", "退出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
